# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\"$\n\x11SingleBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\".\n\x0f\x42ookListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"G\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x14\n\x0cpublish_date\x18\x04 \x01(\t\"(\n\x10\x42ookListResponse\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book\")\n\x12SingleBookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book2o\n\x05\x42ooks\x12\x35\n\nSingleBook\x12\x12.SingleBookRequest\x1a\x13.SingleBookResponse\x12/\n\x08\x42ookList\x12\x10.BookListRequest\x1a\x11.BookListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINGLEBOOKREQUEST']._serialized_start=15
  _globals['_SINGLEBOOKREQUEST']._serialized_end=51
  _globals['_BOOKLISTREQUEST']._serialized_start=53
  _globals['_BOOKLISTREQUEST']._serialized_end=99
  _globals['_BOOK']._serialized_start=101
  _globals['_BOOK']._serialized_end=172
  _globals['_BOOKLISTRESPONSE']._serialized_start=174
  _globals['_BOOKLISTRESPONSE']._serialized_end=214
  _globals['_SINGLEBOOKRESPONSE']._serialized_start=216
  _globals['_SINGLEBOOKRESPONSE']._serialized_end=257
  _globals['_BOOKS']._serialized_start=259
  _globals['_BOOKS']._serialized_end=370
# @@protoc_insertion_point(module_scope)
